const AIRLINES: Record<string, { name: string; color: string }> = {
  AAL: { name: 'American Airlines', color: '#0078D2' },
  UAL: { name: 'United Airlines', color: '#1B4F9B' },
  DAL: { name: 'Delta Air Lines', color: '#C01933' },
  SWA: { name: 'Southwest Airlines', color: '#304CB2' },
  BAW: { name: 'British Airways', color: '#075AAA' },
  AFR: { name: 'Air France', color: '#002157' },
  DLH: { name: 'Lufthansa', color: '#05164D' },
  SIA: { name: 'Singapore Airlines', color: '#1B3D6E' },
  THA: { name: 'Thai Airways', color: '#4A0072' },
  CPA: { name: 'Cathay Pacific', color: '#006564' },
  JAL: { name: 'Japan Airlines', color: '#C8102E' },
  ANA: { name: 'All Nippon Airways', color: '#1A3F7A' },
  KAL: { name: 'Korean Air', color: '#00276C' },
  QFA: { name: 'Qantas', color: '#EE0000' },
  UAE: { name: 'Emirates', color: '#D4282A' },
  QTR: { name: 'Qatar Airways', color: '#5C0632' },
  ETH: { name: 'Ethiopian Airlines', color: '#009A44' },
  TUR: { name: 'Turkish Airlines', color: '#E3000B' },
  EIN: { name: 'Ryanair', color: '#073590' },
  EZY: { name: 'easyJet', color: '#FF6600' },
  IBE: { name: 'Iberia', color: '#D10019' },
  FIN: { name: 'Finnair', color: '#003580' },
  SAS: { name: 'SAS Scandinavian', color: '#000080' },
  KLM: { name: 'KLM', color: '#00A1DE' },
  ACA: { name: 'Air Canada', color: '#F01428' },
  TAM: { name: 'LATAM Brasil', color: '#1C1464' },
  LAN: { name: 'LATAM Chile', color: '#1B1464' },
  AMX: { name: 'Aeromexico', color: '#004B87' },
  CMP: { name: 'Copa Airlines', color: '#0032A0' },
  AVA: { name: 'Avianca', color: '#E4002B' },
  TAP: { name: 'TAP Air Portugal', color: '#006600' },
  AZA: { name: 'ITA Airways', color: '#00205B' },
  BEL: { name: 'Brussels Airlines', color: '#003580' },
  SWR: { name: 'Swiss International', color: '#E2001A' },
  ICE: { name: 'Icelandair', color: '#003087' },
  NOR: { name: 'Norwegian', color: '#C8102E' },
  VYG: { name: 'Virgin Atlantic', color: '#D6001C' },
  VIR: { name: 'Virgin Australia', color: '#E0001B' },
  PAL: { name: 'Philippine Airlines', color: '#0033A0' },
  MAS: { name: 'Malaysia Airlines', color: '#C50025' },
  GAR: { name: 'Garuda Indonesia', color: '#006CB7' },
  THY: { name: 'Thai AirAsia X', color: '#FF0000' },
  AXM: { name: 'AirAsia', color: '#FF0000' },
  CEB: { name: 'Cebu Pacific', color: '#FEDF00' },
  HND: { name: 'Hawaiian Airlines', color: '#4C2B8B' },
  JBU: { name: 'JetBlue', color: '#003087' },
  ASA: { name: 'Alaska Airlines', color: '#01426A' },
  FFT: { name: 'Frontier Airlines', color: '#007A33' },
  NKS: { name: 'Spirit Airlines', color: '#FFD200' },
  HAL: { name: 'Hawaiian Airlines', color: '#4C2B8B' },
  AIC: { name: 'Air India', color: '#E31937' },
  IGO: { name: 'IndiGo', color: '#005DAA' },
  SEJ: { name: 'SpiceJet', color: '#D91C2E' },
  SHI: { name: 'Air India Express', color: '#E31937' },
}

export function lookupAirline(callsign: string): { name: string; color: string } {
  const prefix = callsign.substring(0, 3).toUpperCase()
  return AIRLINES[prefix] ?? { name: prefix, color: '#e8a020' }
}
